### ISSUE TITLE
Uncaught Error: Can't save a buffer with no file

### ISSUE THREAD

**Issue by ridhohariono** [livace/atom-gpp#6]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 10 Home
**Thrown From**: [gpp](https://github.com/livace/atom-gpp) package 0.4.3

### Stack Trace

Uncaught Error: Can't save a buffer with no file

```
At C:\Users\Ridho\AppData\Local\atom\app-1.29.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:1326

Error: Can't save a buffer with no file
    at TextBuffer.module.exports.TextBuffer.saveTo (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:1326:21)
    at TextBuffer.module.exports.TextBuffer.save (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:1310:25)
    at TextEditor.save (~/AppData/Local/atom/app-1.29.0/resources/app/src/text-editor.js:1173:38)
    at Object.compile (/packages/gpp/index.js:19:12)
    at /packages/gpp/index.js:429:18)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.29.0/resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.29.0/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -8:22.4.0 editor:newline (input.hidden-input)
     -8:19 core:move-right (input.hidden-input)
     -8:17.2.0 editor:newline (input.hidden-input)
     -8:15.8.0 snippets:next-tab-stop (input.hidden-input)
     -8:15.8.0 snippets:expand (input.hidden-input)
     -8:15.8.0 editor:indent (input.hidden-input)
  5x -8:11.7.0 core:backspace (input.hidden-input)
     -8:02.3.0 core:move-right (input.hidden-input)
     -8:01.0 editor:newline (input.hidden-input)
     -7:58.6.0 core:backspace (input.hidden-input)
  2x -7:55.2.0 editor:newline (input.hidden-input)
  5x -7:50.1.0 core:backspace (input.hidden-input)
  2x -7:44.3.0 editor:newline (input.hidden-input)
  3x -7:33.7.0 gpp:compile-run (input.hidden-input)
```

### Non-Core Packages

```
gpp 0.4.3 
```

**Comment by livace** [comment]
Fixed in 0.4.4
