### ISSUE TITLE
Uncaught Callback must be a function

### ISSUE THREAD

**Issue by ulmee** [livace/atom-gpp#9]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 3.1.1
**OS**: "Manjaro Linux"
**Thrown From**: [gpp](https://github.com/livace/atom-gpp) package 0.4.3

### Stack Trace

Uncaught Callback must be a function

```
At fs.js:157

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:157:9)
    at Object.fs.writeFile (fs.js:1290:14)
    at ChildProcess.child.on (/packages/gpp/index.js:57:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close [as _onclose] (net.js:596:12)
```

### Commands

```
  3x -1:58 core:backspace (input.hidden-input)
     -1:55.8.0 core:move-right (input.hidden-input)
     -1:55.7.0 core:move-down (input.hidden-input)
  2x -1:55.2.0 core:backspace (input.hidden-input)
  2x -1:53.1.0 editor:newline (input.hidden-input)
  6x -1:48.8.0 core:backspace (input.hidden-input)
     -1:43.6.0 core:move-right (input.hidden-input)
  3x -1:42.6.0 core:backspace (input.hidden-input)
 11x -1:37.1.0 core:move-left (input.hidden-input)
     -1:34.1.0 editor:consolidate-selections (input.hidden-input)
     -1:34.1.0 core:cancel (input.hidden-input)
     -1:33.3.0 core:save (input.hidden-input)
     -1:31.5.0 gpp-compiler:compile (input.hidden-input)
     -0:39.6.0 core:confirm (input.hidden-input)
     -0:16.7.0 core:save (div.tool-panel.tree-view)
     -0:05.4.0 gpp:compile-run (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
gpp 0.4.3 
ide-python 1.2.0 
python-debugger 0.2.0 
```

**Comment by sharp-rat27q** [comment]
Same issue.

**Comment by piotrkrysiak** [comment]
Anybody know how to fix it?

**Comment by joshiCoding** [comment]
instead of gpp-compiler to run c++ code you can use xcode to run (after gpp to compile). Its better and easy
